site_name: HU-DataLab

# Documentation and theme
docs_dir: 'docs'
copyright: 'Copyright © 2021  HU-DataLab.'

theme:
  name: material
  language: ja
  favicon: images/logo.png
  logo: images/logo.png
  palette:
    - scheme: default
      primary: blue grey
      toggle:
        icon: material/toggle-switch-off-outline
        name: Switch to dark mode
    - scheme: slate 
      primary: blue grey
      toggle:
        icon: material/toggle-switch
        name: Switch to light mode

# Extensions
markdown_extensions:
  - admonition
  - attr_list

extra:
  search:
      language: 'jp'
  alternate:
    - name: English
      link: /en/
      lang: en
    - name: 日本語
      link: /ja/
      lang: ja


